### ISSUE TITLE
Upgrade to supported Node version

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/image-proc#12]
Switch to node:4, node:6, or node:8 in [Dockerfile](https://github.com/zooniverse/static-crop/blob/master/Dockerfile#L1).

**Comment by camallen** [comment]
i was thinking about this moving to open-faas if we can as well.

**Comment by adammcmaster** [comment]
Probably a good idea, but either way we'll need to do the same work to make sure it's compatible with a newer node version.

**Comment by eatyourgreens** [comment]
Closed by #16.
