### ISSUE TITLE
Support creating composite subject images

### ISSUE THREAD

**Issue by yogaraptor** [zooniverse/image-proc#2]
Projects that need multiple images per subject currently hand-assemble a single image containing those images.

Looks like a job for ImageMagick's [montage](http://imagemagick.org/script/montage.php) command.

(Will assign self when have permissions)

**Comment by yogaraptor** [comment]
Oops, [rsms/node-imagemagick](https://github.com/rsms/node-imagemagick) doesn't support `montage`. [aheckmann/gm](https://github.com/aheckmann/gm) does though - will build new feature using this - feels like we should then migrate the existing tasks (crop, resize) to use that too - what d'you reckon @camallen?

**Comment by camallen** [comment]
I should have that dependency already installed,https://github.com/zooniverse/static-crop/blob/ee4c38b3462b876237a2b169062f1b60e1cea3ac/package.json#L13 as it's what i build the crop tool with.  There are some legacy tools that i left in that use the imagemagic lib.

**Comment by camallen** [comment]
e.g. here https://github.com/zooniverse/static-crop/blob/master/server.js#L97

**Comment by yogaraptor** [comment]
That's me being super unobservant. Good news though.

**Comment by camallen** [comment]
montage away ;)

**Comment by yogaraptor** [comment]
So ImageMagick kindly sets sensible defaults for grid layout depending on number of input images:

| Num Images | Tile Setting |
| --- | --- |
| 1 | 1x1 |
| 2 | 2x1 |
| 3 | 3x1 |
| 4 | 2x2 |
| 5 - 6 | 3x2 |
| 7 - 8 | 4x2 |

GraphicsMagick, which the `gm` module uses by default, isn't so kind. It defaults to a 4x5 grid no matter the input image count. We can either:
- Use ImageMagick for the montage handler (`require('gm').subClass({imageMagick:true})`). Don't like the idea of using both, and ImageMagick's performance is apparently sub-optimal compared to GM.
- Use GM and re-implement the "best-guess" rules ourselves
- Use GM, don't do any guessing and require the layout as a parameter on the request (we'd need the parameter as an override in any case, so no extra effort here)

**Comment by camallen** [comment]
i'd do the first point from the above list and optimize if / when we need to. should be fine for prototyping and lets see how it performs.

**Comment by yogaraptor** [comment]
Switched to IM for montage in https://github.com/itsravenous/static-crop/commit/ee4c38b3462b876237a2b169062f1b60e1cea3ac

**Comment by yogaraptor** [comment]
Quick note - I can't for the life of me get `montage` to output a non-empty stream, so the handler currently writes a file in `montages/` with a unique hashed name based on the input images. I'm pretty sure this isn't great (concurrency?) and should change at some point.

**Comment by camallen** [comment]
@itsravenous pretty sure this was finished and merged via #3 re-open if not.

**Comment by yogaraptor** [comment]
@camallen yep, it's sub-optimal because it writes the montage to disk rather than streaming to client, but it's implemented at least.
